### PR TITLE
fix: crash when initialising compiler and forks

### LINKED ISSUE #630: WebSocket connection error when trying to load bundle
Hi, when I am running the packager and try to load via either a simulator or a physical device, I get the error below. This started happening after I upgraded to @haul-bundler/cli instead of "haul" package. I am running windows with an android emulator. The error also occurs when the debugger is attached, and also when I try to bundle with `--eager android`.

How can I get this to work or figure out what is going wrong?

````
done ▶︎ Packager server running on http://localhost:8081
info ▶︎ Compiling bundle "index" for platform android
done ▶︎ Successfully run: adb reverse tcp:8081 tcp:8081
error ▶︎ events.js:174
      throw er; // Unhandled 'error' e
error ▶︎ vent


Error: connect UNKNOWN //pipe/tmp/HAUL_SOCKET_43401_.socket
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at ClientRequest.req.on (C;\path\to\project\packages\react-native-app\node_modules\@haul-bundler\core-legacy\node_modules\ws\lib\websocket.js:568:15)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback **(internal/process/next_tick.js:63:19)`**
```

### PR DESCRIPTION
**Pull request by zamotany**
Fixes #630

### CODE REVIEW

File: packages/haul-core-legacy/src/compiler/Fork.js [hunk 1]
```diff
@@ -58,17 +65,15 @@ module.exports = class Fork extends EventEmitter {
...
-    this.enqueuedMessages = [];
-    this.platform = platform;
+    const { port } = transportServer.address();
     this.process = createForkProcess(
-      platform,
+      this.platform,
       __dirname,
-      transportServer.options.server.address(),
-      options
+      `localhost:${port}`,
```
Comment (thymikee) [inline packages/haul-core-legacy/src/compiler/Fork.js]: is setting this to hardcoded localhost is intended?

Comment (zamotany) [reply packages/haul-core-legacy/src/compiler/Fork.js]: Yes, I have to supply some host, and the host from `transportServer` is just `::` which is invalid. This server will always run on the same machine and Haul main process. Even if the haul is run on different machine than the app or in a remote location the `localhost` should point to the same machine as Haul main process is running on.
