### PR TITLE
Properly resolve dev server origin

### LINKED ISSUE #379: [ Android ] Unable to hot reload whilst debugging JS remotely
### Current Behaviour
Run the following command 
`yarn run haul start --platform android`
The app bundles successfully however when trying to hot reload components , I am receiving the following errors 
`http://10.0.2.2:8081/0.508ca35a4baeb9f81480.hot-update.js net::ERR_CONNECTION_TIMED_OUT`

```
[HMR] Update check failed: Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://10.0.2.2:8081/0.508ca35a4baeb9f81480.hot-update.js' failed to load.
    at hotDownloadUpdateChunk (eval at evalJS (http://localhost:8081/debuggerWorker.js:64:11), <anonymous>:9:12)
    at hotEnsureUpdateChunk (eval at evalJS (http://localhost:8081/debuggerWorker.js:64:11), <anonymous>:270:13)
    at eval (eval at evalJS (http://localhost:8081/debuggerWorker.js:64:11), <anonymous>:241:14)
    at tryCallOne (webpack-internal:///./node_modules/promise/setimmediate/core.js:37:12)
    at eval (webpack-internal:///./node_modules/promise/setimmediate/core.js:123:15)
    at eval (webpack-internal:///./node_modules/react-native/Libraries/Core/Timers/JSTimers.js:1:4804)
    at _callTimer (webpack-internal:///./node_modules/react-native/Libraries/Core/Timers/JSTimers.js:1:2609) 
```

Please note that in the terminal I see 
`GET /508ca35a4baeb9f81480.hot-update.json 200 43 - 0.451 ms` 
However the network panel in the debugger seems to be trying to load hot-update.js

### Expected Behaviour 

Components should be able to hot reload as they do on iOS

### Haul Configuration (webpack.haul.js) 
```const path = require('path');

module.exports = ({ platform, root }, defaults) => ({
  entry: `./index.${platform}.js`,
  resolve: {
    ...defaults.resolve,
    alias: {
      ...defaults.resolve.alias,
      Config: path.join(root, 'config'),
      Components: path.join(root, 'app', 'components'),
      Routes: path.join(root, 'app', 'routes'),
      Util: path.join(root, 'app', 'util'),
      Reducers: path.join(root, 'app', 'reducers'),
    },
  },
  module: {
    ...defaults.module,
    rules: [
      {
        test: /\.js?$/,
        include: '/node_modules/seamless-immutable',
        exclude: '/node_modules/',
        use: [
          {
            loader: 'react-hot-loader/webpack',
          },
        ],
      },
    ].concat(defaults.module.rules || []),
  },
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.13
| react-native     |  0.49.0
| node             |  9.3.0
| npm or yarn      | yarn(1.3.2)

### PR DESCRIPTION
**Pull request by zamotany**
Fixes #379

### CODE REVIEW

File: src/utils/polyfillEnvironment.js [hunk 1]
```diff
@@ -36,21 +36,31 @@ require('InitializeCore'); // eslint-disable-line import/no-unresolved
...
-  const [protocol, , origin] = scriptURL.split('/');
-  devServerOrigin = `${protocol}//${origin}`;
-}
+if (process.env.NODE_ENV !== 'production') {
+  let protocol;
+  let origin;
+
+  // If remote debugger is attached, we have access to `window` object
+  // from which we can get `protocol` and `origin` of dev server.
+  if (typeof window !== 'undefined' && window.location) {
```
Comment (satya164) [inline src/utils/polyfillEnvironment.js]: Can we do this as the fallback (do we actually need to?) instead of the preferred method?

Comment (zamotany) [reply src/utils/polyfillEnvironment.js]: No it must be a preferred way otherwise, this fallback will never gets executed.

Comment (satya164) [reply src/utils/polyfillEnvironment.js]: @zamotany can `scriptURL` return wrong value when you're debugging? can you add a comment on why this is the case? because I have no idea.

Comment (zamotany) [reply src/utils/polyfillEnvironment.js]: `scriptURL`: `http://10.0.2.2:8081/...` vs debugger host `http://localhost:8081`. You need to use `localhost` because `importScripts` is executed in debugger context. Otherwise you would get CSP error.

Comment (satya164) [reply src/utils/polyfillEnvironment.js]: @zamotany thanks! add a comment please :D
