### PR TITLE
Fix scriptUrl for production build

### LINKED ISSUE #349: scriptURL is null when building for Release with Xcode
### Current Behavior

When building with the release build configuration in Xcode, I'm getting the following build error:
```
Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: null is not an object (evaluating 't.match(/(^.+)\/index/)[1]')
```
The error is referring to the minified version of [this line](https://github.com/callstack/haul/blob/172c93acf759e43ee93f1825e683a420a9f8784c/src/utils/polyfillEnvironment.js#L45), so it seems that `NativeModules.SourceCode.scriptURL` being imported from react-native is `null`.

I'm getting this when using haul version 1.0.0-beta-12. With 1.0.0-beta-11, it works just fine (it doesn't include the line that is causing the error).

### Expected Behavior

The build should complete without error as it does in beta-11.

### Haul Configuration (webpack.haul.js)

```
const eslintFormatter = require('react-dev-utils/eslintFormatter')
const paths = require('./paths')

module.exports = ({ platform }, defaults) => ({
  entry: `./index.js`,
  module: {
    ...defaults.module,
    rules: [
      ...defaults.module.rules,
      {
        test: /\.(js|jsx)$/,
        enforce: 'pre',
        use: [
          {
            options: {
              formatter: eslintFormatter,
            },
            loader: require.resolve('eslint-loader'),
          },
        ],
        include: paths.appSrc,
      },
      {
        test: /\.graphql$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader',
      },
    ],
  },
})
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta-12
| react-native     |  0.52.0
| node             | 8.9.4
| npm or yarn      | yarn

### PR DESCRIPTION
**Pull request by czystyl**
## Summary

For production build regexp not matched anything and `scriptURL.match(/(^.+)\/index/)[1]` throws error because match was `null`, so i added statement for checking match and return null if not matched.

Fixes #349

### CODE REVIEW

File: src/utils/polyfillEnvironment.js [hunk 1]
```diff
@@ -42,7 +42,9 @@ const scriptURL = require('react-native').NativeModules.SourceCode.scriptURL; //
 // or Android device it will be `localhost:<port>` but when using real iOS device
 // it will be `<ip>.xip.io:<port>`. Thus the code below ensure we connect and download
 // manifest/hot-update from a valid origin.
-global.DEV_SERVER_ORIGIN = scriptURL.match(/(^.+)\/index/)[1];
+const match = scriptURL.match(/(^.+)\/index/);
```
Comment (Krizzu) [inline src/utils/polyfillEnvironment.js]: Let's do sanity check here

Comment (Krizzu) [inline src/utils/polyfillEnvironment.js]: Let's do a sanity check here

Comment (Krizzu) [inline src/utils/polyfillEnvironment.js]: Let's do sanity check here

`const match = scriptURL && scriptURL.match(/(^.+)\/index/);`

Comment (thymikee) [reply src/utils/polyfillEnvironment.js]: Based on @czystyl findings `scriptURL` is always set, it's just different for development and production envs

Comment (Krizzu) [reply src/utils/polyfillEnvironment.js]: Would it be a problem to do that sanity check tho?

**Comment by Krizzu** [comment]
Don't forget to add yourself to contribution list!

File: src/utils/polyfillEnvironment.js (hunk 1 above)
Comment (czystyl) [reply src/utils/polyfillEnvironment.js]: That's true

Comment (czystyl) [reply src/utils/polyfillEnvironment.js]: I added this check if RN change something.
